Dataset - https://www.kaggle.com/datasets/utkarsharya/ecommerce-purchases

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/Ecommerce Purchases')

In [3]:
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

1. Show top 10 rows of the dataset

In [4]:
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

2. check last 10 rows of the dataset

In [5]:
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

3. Checking number of rows and columns in dataset

In [6]:
df.shape

(10000, 14)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

4. checking datatype of each column

In [7]:
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

5. Checking null or missing values in each column

In [8]:
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

6. Highest and lowest purchase prices

In [12]:
df['Purchase Price'].max()

99.99

In [13]:
df['Purchase Price'].min()

0.0

7. Average Purchase Price

In [14]:
df['Purchase Price'].mean()

50.347302

8. How many people have French 'fr' as their language?

In [20]:
df['Language']

0       el
1       fr
2       de
3       es
4       es
        ..
9995    it
9996    pt
9997    el
9998    es
9999    el
Name: Language, Length: 10000, dtype: object

In [23]:
df[df['Language'] == 'fr']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
53,"PSC 9431, Box 7059\nAPO AA 29285-1363",14 qD,AM,Opera/9.34.(X11; Linux x86_64; it-IT) Presto/2...,"Higgins, Cardenas and Kennedy",869972604798355,08/17,157,JCB 16 digit,amorales@yahoo.com,Technical author,44.108.117.122,fr,10.41
76,"49206 Campbell Port\nNorth Cliffordshire, HI 3...",71 iu,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_9...,Jacobs-Tucker,6011343518820988,01/17,806,Voyager,eperez@hotmail.com,Paramedic,210.207.58.168,fr,57.34
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9947,"32827 Carl Inlet\nSouth Nicole, NY 38081-6636",40 Dp,PM,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,Pruitt-Flores,3158564208754951,03/17,386,Mastercard,josephsmith@gmail.com,Textile designer,198.68.38.23,fr,49.61
9951,"518 Brown Dam\nGarciaside, IN 33057",71 wq,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Crosby, Vasquez and Ballard",5256758441931287,12/17,146,VISA 16 digit,cjennings@yahoo.com,"Lighting technician, broadcasting/film/video",58.12.83.1,fr,57.59
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9980,"6061 Dave Lights\nPhillipsview, UT 40500",25 Mv,AM,Opera/8.58.(Windows NT 5.0; it-IT) Presto/2.9....,Cortez-Frye,6011944199756993,12/24,755,JCB 15 digit,mark74@kirby-stewart.org,Textile designer,110.103.77.195,fr,16.05

In [25]:
len(df[df['Language'] == 'fr'])

1097

9. Which are the Job title contains Artist.

In [31]:
df['Job'].str.contains('artist')

0       False
1       False
2       False
3       False
4        True
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Job, Length: 10000, dtype: bool

In [39]:
len(df[df['Job'].str.contains('artist',case=False)])

40

10. Finding a Person with IP Address 24.140.33.94

In [43]:
df['IP Address']

0       149.146.147.205
1          15.160.41.51
2        132.207.160.22
3          30.250.74.19
4          24.140.33.94
             ...
9995      29.73.197.114
9996     121.133.168.51
9997      156.210.0.254
9998       55.78.26.143
9999    176.119.198.199
Name: IP Address, Length: 10000, dtype: object

In [46]:
df[df['IP Address'] == '24.140.33.94']['Email']

4    christopherwright@gmail.com
Name: Email, dtype: object

11. How many people have Discover as their credit card provider and made a purchase above 50?

In [49]:
df[df['CC Provider']=='Discover'].count()

Address             817
Lot                 817
AM or PM            817
Browser Info        817
Company             817
Credit Card         817
CC Exp Date         817
CC Security Code    817
CC Provider         817
Email               817
Job                 817
IP Address          817
Language            817
Purchase Price      817
dtype: int64

In [52]:
len(df[(df['CC Provider']=='Discover') & (df['Purchase Price'] > 50)])

437

12. Find the email of the person with the following credit card number: 342945015358701

In [54]:
df[df['Credit Card'] == 342945015358701]['Email']

9995    iscott@wade-garner.com
Name: Email, dtype: object

13. How many people purchase during AM and How many people purchase during PM?

In [56]:
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

14. How many people have a credit card that expires in 2022?

In [57]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [58]:
df['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [63]:
def card_exp():
    count = 0
    for date in df['CC Exp Date']:
        if date.split('/')[1]=='22':
            count=count+1
    print(count)

In [64]:
card_exp()

996

15. Top 5 most popular email providers

In [65]:
list1 = []
for email in df['Email']:
    list1.append(email.split('@')[1])

In [66]:
list1

['yahoo.com',
 'reed.com',
 'morales-harrison.com',
 'olson-robinson.info',
 'gmail.com',
 'gmail.com',
 'yahoo.com',
 'parks.info',
 'rasmussen.com',
 'hunt-huerta.com',
 'hotmail.com',
 'coleman.com',
 'hotmail.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'wilson.com',
 'hall.com',
 'yahoo.com',
 'gmail.com',
 'smith.info',
 'hotmail.com',
 'gmail.com',
 'gardner-meadows.com',
 'yahoo.com',
 'mooney.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'atkinson.com',
 'yahoo.com',
 'carey-davis.com',
 'mcdowell.com',
 'walsh.com',
 'frederick.info',
 'boyd-english.org',
 'wells-carlson.info',
 'dickerson.com',
 'yahoo.com',
 'gmail.com',
 'martinez-thomas.com',
 'yahoo.com',
 'chambers.com',
 'gmail.com',
 'glenn.org',
 'allen.com',
 'gmail.com',
 'obrien.org',
 'cook-castillo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'lawrence-warren.biz',
 'morris.com',
 'howe.com',
 'walton.org',
 'jones.biz',
 'gmail.com',
 'simmons-gutierrez.org',
 'yahoo.com',
 'gardner-anderson.com',
 'gmail.com',
 'hotmail.com',
 'green.com',
 'wallace-moore.info',
 'wiley.net',
 'rodgers-morris.biz',
 'johnson.info',
 'hotmail.com',
 'gmail.com',
 'reyes.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'beasley-murphy.net',
 'donovan-brown.biz',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'weber-williams.com',
 'yahoo.com',
 'smith-brown.info',
 'fleming.info',
 'yahoo.com',
 'gmail.com',
 'brown.com',
 'hotmail.com',
 'harrison-brown.info',
 'kim.biz',
 'watkins.com',
 'thomas.net',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'cochran.com',
 'gmail.com',
 'yahoo.com',
 'jackson-johnson.biz',
 'woods-nunez.biz',
 'price.com',
 'gmail.com',
 'white.com',
 'hotmail.com',
 'lowe.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'allen-kennedy.org',
 'hotmail.com',
 'nelson.com',
 'long.net',
 'hotmail.com',
 'yahoo.com',
 'cervantes-smith.net',
 'silva-cohen.com',
 'wilson-wright.biz',
 'allen.com',
 'yahoo.com',
 'aguirre.com',
 'scott.net',
 'nelson.com',
 'gmail.com',
 'gmail.com',
 'henderson-peterson.org',
 'yahoo.com',
 'yahoo.com',
 'james.biz',
 'stewart.org',
 'martinez.com',
 'yahoo.com',
 'yahoo.com',
 'wright.com',
 'lopez.net',
 'yahoo.com',
 'carlson.net',
 'bean-mcdaniel.com',
 'bennett.com',
 'mosley-brown.com',
 'yahoo.com',
 'fisher.com',
 'guerrero.net',
 'cardenas.com',
 'yahoo.com',
 'smith-conner.org',
 'sherman-perry.org',
 'matthews.com',
 'gmail.com',
 'valenzuela-mccarty.org',
 'wagner.com',
 'williams.info',
 'yahoo.com',
 'gmail.com',
 'beck-hickman.com',
 'hotmail.com',
 'perez-acosta.com',
 'dunn.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'collier.com',
 'yahoo.com',
 'hood.com',
 'yahoo.com',
 'taylor-moore.net',
 'gmail.com',
 'gmail.com',
 'sanchez-chambers.net',
 'gmail.com',
 'flynn-callahan.com',
 'yahoo.com',
 'good.com',
 'scott.com',
 'french-richards.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'wright.com',
 'davenport-zimmerman.com',
 'gray.com',
 'hotmail.com',
 'hotmail.com',
 'olson.com',
 'shaw.com',
 'murray-jones.com',
 'cruz.com',
 'alexander-villegas.com',
 'brown.net',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'delacruz.biz',
 'beasley.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'griffith.com',
 'hotmail.com',
 'smith.org',
 'green-lee.com',
 'hotmail.com',
 'bauer.com',
 'kane.com',
 'mullins-fletcher.com',
 'gmail.com',
 'knight.com',
 'gmail.com',
 'newman.com',
 'bass.com',
 'hotmail.com',
 'spence-browning.com',
 'caldwell-strickland.com',
 'bush.org',
 'yahoo.com',
 'jones-white.com',
 'suarez.com',
 'elliott.com',
 'sanchez.com',
 'yahoo.com',
 'mitchell-daugherty.com',
 'foster.org',
 'griffin.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'robinson.org',
 'smith-bates.com',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'ellis.com',
 'hotmail.com',
 'murray.com',
 'gmail.com',
 'yahoo.com',
 'moss.info',
 'yahoo.com',
 'weaver.com',
 'hill-bentley.net',
 'gmail.com',
 'rivera-bishop.com',
 'hotmail.com',
 'west-phillips.info',
 'hotmail.com',
 'gmail.com',
 'phillips-johnson.org',
 'gmail.com',
 'lambert.com',
 'hotmail.com',
 'reyes.net',
 'wade-butler.org',
 'henderson.com',
 'spence.com',
 'hotmail.com',
 'powell.net',
 'johnson.biz',
 'castro.org',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'summers-boyd.com',
 'carter.com',
 'yahoo.com',
 'hotmail.com',
 'brooks.net',
 'obrien.com',
 'espinoza.org',
 'yahoo.com',
 'hicks.com',
 'yahoo.com',
 'gmail.com',
 'flynn.info',
 'harvey-hunt.com',
 'acevedo-pena.biz',
 'daniels.com',
 'gmail.com',
 'roberts.com',
 'kim.biz',
 'yahoo.com',
 'gmail.com',
 'davis.com',
 'mills.com',
 'butler-lozano.com',
 'martinez.net',
 'carter-adams.biz',
 'gmail.com',
 'edwards.com',
 'smith-butler.net',
 'yahoo.com',
 'nguyen.org',
 'yahoo.com',
 'yahoo.com',
 'brown.com',
 'shaw.net',
 'hotmail.com',
 'smith.biz',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'lopez.com',
 'mccormick-kirby.com',
 'sellers.com',
 'smith.net',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'hawkins-green.net',
 'york-atkins.com',
 'hotmail.com',
 'yahoo.com',
 'green.com',
 'gmail.com',
 'garcia.com',
 'cardenas.net',
 'yahoo.com',
 'kerr-wilson.com',
 'gmail.com',
 'richardson.com',
 'yahoo.com',
 'hart.com',
 'yahoo.com',
 'anthony.com',
 'griffin-thomas.com',
 'hotmail.com',
 'moore.com',
 'ross.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'lee.net',
 'gmail.com',
 'hotmail.com',
 'graham.com',
 'yahoo.com',
 'jackson.com',
 'yahoo.com',
 'hotmail.com',
 'frey-ward.com',
 'sanford.com',
 'gmail.com',
 'moreno.com',
 'carson.net',
 'hotmail.com',
 'blackburn-lucero.com',
 'jackson.net',
 'kelley-arnold.com',
 'osborne.info',
 'valenzuela.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'rodriguez.com',
 'hotmail.com',
 'stevenson-curry.biz',
 'gmail.com',
 'hotmail.com',
 'davis-mcdonald.com',
 'jones.net',
 'hotmail.com',
 'henry.org',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'pugh.com',
 'ballard.com',
 'thompson.com',
 'gmail.com',
 'brown.net',
 'bates-wood.biz',
 'jordan-pierce.com',
 'gmail.com',
 'yahoo.com',
 'velasquez.net',
 'figueroa.info',
 'hotmail.com',
 'hotmail.com',
 'osborne.info',
 'sanchez.com',
 'merritt-york.com',
 'yahoo.com',
 'johnson-white.biz',
 'gonzalez.org',
 'miller.com',
 'yahoo.com',
 'rhodes.com',
 'yahoo.com',
 'hotmail.com',
 'potts-rose.net',
 'hotmail.com',
 'moore.info',
 'yahoo.com',
 'barrera.org',
 'page.com',
 'gmail.com',
 'vaughn.com',
 'moore.org',
 'martinez-williams.net',
 'gmail.com',
 'mcclure.biz',
 'carr.com',
 'yahoo.com',
 'gonzalez.com',
 'hotmail.com',
 'williams.com',
 'thomas.biz',
 'andrews.com',
 'herrera-miller.biz',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'allen.org',
 'thomas.com',
 'fuller-johnson.com',
 'robinson.com',
 'armstrong.biz',
 'yahoo.com',
 'yahoo.com',
 'robinson.com',
 'yahoo.com',
 'hotmail.com',
 'rodriguez-hernandez.com',
 'gmail.com',
 'foster.net',
 'dalton.net',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'castro-whitaker.net',
 'hill.biz',
 'stein-cox.com',
 'vargas-brown.com',
 'melton-duke.com',
 'yahoo.com',
 'yahoo.com',
 'lopez.com',
 'moran.com',
 'brown.com',
 'hotmail.com',
 'guzman-davis.com',
 'gmail.com',
 'allen.com',
 'gonzalez.net',
 'cox.com',
 'sanders.org',
 'yahoo.com',
 'jensen.info',
 'yahoo.com',
 'hotmail.com',
 'reed.com',
 'meyer-palmer.org',
 'hotmail.com',
 'kramer.com',
 'peters-green.com',
 'perez.info',
 'berry-davis.com',
 'hotmail.com',
 'johnson.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'murray.info',
 'hotmail.com',
 'lindsey.net',
 'roberts.net',
 'gmail.com',
 'yahoo.com',
 'smith-ford.biz',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'fritz.com',
 'gmail.com',
 'clark-simpson.com',
 'gmail.com',
 'hotmail.com',
 'patton.com',
 'oconnor-dixon.com',
 'yahoo.com',
 'yahoo.com',
 'murray.net',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'moore-robinson.com',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'moore-lutz.com',
 'deleon-ortega.org',
 'page.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'livingston.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'wright.net',
 'hotmail.com',
 'gmail.com',
 'schwartz.info',
 'cook.com',
 'richardson-flores.com',
 'brown-bean.com',
 'wilkinson.com',
 'richardson.biz',
 'figueroa-jones.com',
 'yahoo.com',
 'hotmail.com',
 'choi-morris.com',
 'gmail.com',
 'lee.com',
 'torres.biz',
 'owen-gross.com',
 'hotmail.com',
 'deleon.com',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'clark.com',
 'baker.com',
 'smith-nunez.info',
 'tyler.com',
 'yahoo.com',
 'aguilar-nelson.com',
 'holder.com',
 'livingston-smith.biz',
 'smith-reid.com',
 'hotmail.com',
 'gmail.com',
 'rodriguez.com',
 'yahoo.com',
 'hurst.com',
 'smith-collins.biz',
 'hotmail.com',
 'wright.com',
 'gmail.com',
 'hotmail.com',
 'tran-mccoy.org',
 'mclaughlin.com',
 'wilson.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'barnes.com',
 'yahoo.com',
 'yahoo.com',
 'browning.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'palmer-mckee.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'johnson-oliver.net',
 'carpenter.info',
 'brown-wilson.net',
 'martinez-malone.com',
 'chung.com',
 'alvarez.com',
 'perez.com',
 'gmail.com',
 'jones.com',
 'aguilar.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'garrison-woodard.com',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'adams.com',
 'reid.com',
 'gmail.com',
 'meza-jackson.org',
 'curtis.com',
 'marquez-castillo.biz',
 'rangel.net',
 'lewis-brown.net',
 'hotmail.com',
 'hotmail.com',
 'copeland.org',
 'yahoo.com',
 'fritz-gray.com',
 'carson.com',
 'hotmail.com',
 'hotmail.com',
 'haynes.com',
 'gmail.com',
 'stafford.com',
 'hotmail.com',
 'reid.com',
 'cruz.biz',
 'ballard-myers.info',
 'yahoo.com',
 'hernandez-nielsen.com',
 'yahoo.com',
 'wagner.com',
 'hotmail.com',
 'yahoo.com',
 'moore.com',
 'russell.com',
 'hughes.com',
 'gmail.com',
 'martin-chavez.com',
 'smith.com',
 'terrell.biz',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'davis.com',
 'steele.net',
 'rose.info',
 'long.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'russell.com',
 'yahoo.com',
 'short.biz',
 'gmail.com',
 'yahoo.com',
 'roach.com',
 'vaughn-sullivan.biz',
 'dean.com',
 'mills.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'walker-morales.com',
 'malone.com',
 'fernandez.com',
 'jackson-pitts.com',
 'yahoo.com',
 'morris.biz',
 'anderson-duke.com',
 'yahoo.com',
 'yahoo.com',
 'hernandez.biz',
 'harris.com',
 'gmail.com',
 'murphy.org',
 'richards.org',
 'gmail.com',
 'gonzales-anderson.com',
 'davenport-garcia.com',
 'hull.info',
 'gmail.com',
 'atkins.biz',
 'martin.com',
 'nguyen-smith.net',
 'bailey.net',
 'black.org',
 'hotmail.com',
 'sanford-lopez.com',
 'kelly.biz',
 'hotmail.com',
 'garcia-pugh.biz',
 'cox.com',
 'yahoo.com',
 'yahoo.com',
 'anderson-werner.biz',
 'hotmail.com',
 'browning-yu.com',
 'yahoo.com',
 'lopez-kelly.com',
 'fernandez-bell.com',
 'campbell.info',
 'gmail.com',
 'manning.org',
 'rollins.com',
 'johnson-long.biz',
 'flynn-williams.com',
 'hotmail.com',
 'winters.info',
 'gmail.com',
 'gmail.com',
 'graham-green.net',
 'hotmail.com',
 'ballard.net',
 'long.com',
 'meyer.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'roberts.com',
 'hotmail.com',
 'hart-reynolds.com',
 'yahoo.com',
 'jimenez.biz',
 'turner-hall.net',
 'yahoo.com',
 'gmail.com',
 'haynes-pollard.info',
 'hotmail.com',
 'yahoo.com',
 'clay.net',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'foster-travis.biz',
 'gmail.com',
 'hotmail.com',
 'price.org',
 'hughes.com',
 'chen-cantu.net',
 'santana.com',
 'long.org',
 'hotmail.com',
 'hotmail.com',
 'smith.net',
 'beard-franco.com',
 'marshall-johnson.net',
 'sherman.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'boone-barton.com',
 'velez.com',
 'gmail.com',
 'johnson-grant.net',
 'hotmail.com',
 'gomez.info',
 'hopkins.biz',
 'silva.com',
 'gmail.com',
 'thomas.org',
 'armstrong-adkins.biz',
 'hotmail.com',
 'ritter.com',
 'holmes-jones.com',
 'walter.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'rodriguez.biz',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'sellers-perez.net',
 'reese-mcintosh.com',
 'jackson.org',
 'medina-reyes.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'duncan-garcia.com',
 'hotmail.com',
 'webster.com',
 'myers.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'gray-mejia.com',
 'clark-garcia.org',
 'wright-walton.com',
 'gmail.com',
 'yahoo.com',
 'smith-harrison.com',
 'hotmail.com',
 'hotmail.com',
 'martin.info',
 'hotmail.com',
 'gmail.com',
 'johnson-schmidt.com',
 'hall-stephens.net',
 'mora.info',
 'coleman.com',
 'hotmail.com',
 'jones-morgan.org',
 'hotmail.com',
 'yahoo.com',
 'robbins-mcdonald.com',
 'gmail.com',
 'hotmail.com',
 'knight.biz',
 'simmons-rasmussen.com',
 'molina.org',
 'smith.biz',
 'jones.com',
 'anderson-thompson.com',
 'taylor.org',
 'gmail.com',
 'yahoo.com',
 'carroll.com',
 'logan.net',
 'best.com',
 'yahoo.com',
 'yahoo.com',
 'gill-flores.com',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'guerrero.com',
 'hotmail.com',
 'yahoo.com',
 'gardner.com',
 'hotmail.com',
 'reed-gonzalez.com',
 'yahoo.com',
 'white.com',
 'hotmail.com',
 'gmail.com',
 'davis.com',
 'clay.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'williams.biz',
 'pearson.com',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'luna-hancock.info',
 'little-branch.info',
 'murphy-berry.com',
 'marshall.com',
 'alvarez.com',
 'rivas-glover.com',
 'sloan.com',
 'gonzalez.com',
 'rivera.org',
 'hotmail.com',
 'moore-martinez.biz',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'morrison-smith.com',
 'gmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'torres.com',
 'hotmail.com',
 'brown.net',
 'hotmail.com',
 'yahoo.com',
 'caldwell.net',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'summers.info',
 'hotmail.com',
 'yahoo.com',
 'rios.com',
 'yahoo.com',
 'gross.com',
 'thompson.com',
 'weber.org',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'andrews.biz',
 'gmail.com',
 'johnson-dean.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'galloway.com',
 'coleman-williams.net',
 'rodriguez.org',
 'stein-hayes.com',
 'hotmail.com',
 'hahn-roberts.com',
 'green.org',
 'hernandez-finley.net',
 'dunlap.net',
 'butler-thompson.net',
 'stone.com',
 'melendez-decker.net',
 'yahoo.com',
 'knapp.info',
 'gonzalez.info',
 'hotmail.com',
 'guerrero.info',
 'burton.com',
 'underwood-jenkins.org',
 'brown.com',
 'yahoo.com',
 'hotmail.com',
 'anderson.net',
 'hotmail.com',
 'hotmail.com',
 'berry.com',
 'rodriguez-yang.com',
 'payne-bell.info',
 'guerrero-shah.com',
 'hotmail.com',
 'hotmail.com',
 'riley.com',
 'gonzalez-gamble.org',
 'craig.com',
 'hotmail.com',
 'lee.org',
 'hotmail.com',
 'haynes-nguyen.com',
 'parker.com',
 'gmail.com',
 'hotmail.com',
 'reeves-cole.biz',
 'hotmail.com',
 'barnes.com',
 'anderson-fleming.biz',
 'myers.biz',
 'henderson.net',
 'goodwin.com',
 'bass-sullivan.info',
 'yahoo.com',
 'hotmail.com',
 'whitney.org',
 'hotmail.com',
 'aguilar.com',
 'gmail.com',
 'gmail.com',
 'brooks.com',
 'hotmail.com',
 'miller.info',
 'stone.net',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'silva-cox.com',
 'hill.net',
 'curtis.com',
 'hotmail.com',
 'hotmail.com',
 'dorsey.org',
 'velazquez.com',
 'yahoo.com',
 'cox-cole.com',
 'duarte.com',
 'gmail.com',
 'hotmail.com',
 'knight.com',
 'hotmail.com',
 'king-blanchard.com',
 ...]

In [68]:
df['temp'] = list1

In [69]:
df['temp'].value_counts()

temp
hotmail.com            1638
yahoo.com              1616
gmail.com              1605
smith.com                42
williams.com             37
                       ...
booker.com                1
woods-allen.biz           1
richards-wilson.com       1
morris-thomas.com         1
wade-garner.com           1
Name: count, Length: 3416, dtype: int64

In [71]:
df['temp'].value_counts().head(5)

temp
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

**Intermediate Level Analysis**
16. What is the average purchase price for each job category? Are there any specific professions that tend to spend more?

In [72]:
avg_purchase_by_job = df.groupby('Job')['Purchase Price'].mean()

In [75]:
print("Average Purchase Price by Job:\n", avg_purchase_by_job)

Average Purchase Price by Job:
 Job
Academic librarian                  47.951818
Accommodation manager               37.038235
Accountant, chartered               52.565500
Accountant, chartered certified     57.945000
Accountant, chartered management    69.082667
                                      ...
Water quality scientist             46.526111
Web designer                        59.764500
Wellsite geologist                  51.309167
Writer                              44.863000
Youth worker                        40.513333
Name: Purchase Price, Length: 623, dtype: float64

17. Spending behavior based on language

In [76]:
avg_purchase_by_language = df.groupby('Language')['Purchase Price'].mean()
print("\nAverage Purchase Price by Language:\n", avg_purchase_by_language)

Average Purchase Price by Language:
 Language
de    50.254485
el    51.555356
en    51.103015
es    49.366977
fr    49.476718
it    50.001004
pt    51.215546
ru    49.927134
zh    50.180198
Name: Purchase Price, dtype: float64

18. Difference in purchase amounts between AM and PM

In [78]:
avg_purchase_by_time = df.groupby('AM or PM')['Purchase Price'].mean()
print("\nAverage Purchase Price by AM/PM:\n", avg_purchase_by_time)

Average Purchase Price by AM/PM:
 AM or PM
AM    50.186511
PM    50.503779
Name: Purchase Price, dtype: float64

19. Most frequently used credit card providers

In [79]:
most_common_cc_provider = df['CC Provider'].value_counts().head(10)
print("\nMost Common Credit Card Providers:\n", most_common_cc_provider)

Most Common Credit Card Providers:
 CC Provider
JCB 16 digit                   1716
VISA 16 digit                  1715
JCB 15 digit                    868
American Express                849
Maestro                         846
Voyager                         829
Discover                        817
Mastercard                      816
VISA 13 digit                   777
Diners Club / Carte Blanche     767
Name: count, dtype: int64

20. Patterns in purchase prices related to credit card expiration

In [80]:
df['CC Exp Year'] = df['CC Exp Date'].apply(lambda x: int(x.split('/')[1]))
avg_purchase_by_exp_year = df.groupby('CC Exp Year')['Purchase Price'].mean()
print("\nAverage Purchase Price by Credit Card Expiration Year:\n", avg_purchase_by_exp_year)

Average Purchase Price by Credit Card Expiration Year:
 CC Exp Year
16    51.549096
17    49.777948
18    49.898080
19    49.736382
20    49.615000
21    50.494205
22    50.263002
23    50.892822
24    51.729274
25    51.175915
26    48.861896
Name: Purchase Price, dtype: float64

21. Correlation between location (IP Address) and purchase price

In [81]:
avg_purchase_by_ip = df.groupby('IP Address')['Purchase Price'].mean()
print("\nAverage Purchase Price by IP Address:\n", avg_purchase_by_ip.head(10))

Average Purchase Price by IP Address:
 IP Address
0.116.212.13     16.82
0.120.197.128    80.31
0.121.5.35       54.46
0.130.253.240    52.29
0.147.206.48     16.44
0.149.55.29      37.93
0.157.56.119     88.21
0.183.107.167    57.43
0.194.110.217    15.16
0.195.65.213     28.40
Name: Purchase Price, dtype: float64

22. Spending analysis based on email domains

In [83]:
df['Email Domain'] = df['Email'].apply(lambda x: x.split('@')[1])
avg_purchase_by_email_domain = df.groupby('Email Domain')['Purchase Price'].mean().head(10)
print("\nAverage Purchase Price by Email Domain:\n", avg_purchase_by_email_domain)

Average Purchase Price by Email Domain:
 Email Domain
acevedo-osborn.com    70.010000
acevedo-pena.biz      94.100000
acosta.biz            13.140000
acosta.com            51.720000
adams-garcia.net      60.210000
adams-peck.info       27.300000
adams-taylor.com      99.700000
adams.com             68.488333
adams.net             69.810000
adams.org             52.660000
Name: Purchase Price, dtype: float64

23. Browser-based analysis of purchase amounts

In [84]:
df['Browser'] = df['Browser Info'].apply(lambda x: x.split()[0])  # Extract browser name
avg_purchase_by_browser = df.groupby('Browser')['Purchase Price'].mean()
print("\nAverage Purchase Price by Browser:\n", avg_purchase_by_browser)

Average Purchase Price by Browser:
 Browser
Mozilla/5.0            50.194543
Opera/8.10.(Windows    35.650000
Opera/8.10.(X11;       48.660000
Opera/8.11.(Windows    46.346667
Opera/8.11.(X11;       44.634286
                         ...
Opera/9.97.(X11;       35.858000
Opera/9.98.(Windows    53.460000
Opera/9.98.(X11;       46.090000
Opera/9.99.(Windows    44.204000
Opera/9.99.(X11;       48.861250
Name: Purchase Price, Length: 360, dtype: float64

24. Company-wise purchase price analysis

In [85]:
avg_purchase_by_company = df.groupby('Company')['Purchase Price'].mean().sort_values(ascending=False).head(10)
print("\nTop Companies by Average Purchase Price:\n", avg_purchase_by_company)

Top Companies by Average Purchase Price:
 Company
Porter, Johnson and Pratt    99.99
Pitts Group                  99.99
Olson-Navarro                99.97
Fitzpatrick Group            99.95
Fisher-Guerrero              99.92
Bond-Oconnor                 99.92
Powell, Martin and Henry     99.91
Fisher-Marshall              99.90
Sweeney-Stephens             99.90
Huang PLC                    99.90
Name: Purchase Price, dtype: float64

25. Security risks by company

In [86]:
potential_security_risks = df.groupby('Company')['CC Security Code'].nunique().sort_values(ascending=False).head(10)
print("\nCompanies with Highest Number of Unique Security Codes:\n", potential_security_risks)

Companies with Highest Number of Unique Security Codes:
 Company
Brown Ltd         15
Smith Group       15
Smith PLC         13
Smith LLC         13
Williams LLC      12
Smith and Sons    11
Davis and Sons    11
Smith Inc         10
Brown Group       10
Johnson Ltd       10
Name: CC Security Code, dtype: int64